spring:
  profiles:
    include: db
  #  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mybox?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
#    username: mybox
#    password: mybox

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.GPOslo: DEBUG

jwt:
  header: Authoriation
  secret: aGVsbG8tbXktbmFtZS1pcy1qYWVoeWVvbi10aGlzLWtleS1pcy12ZXJ5LWltcG9ydGFudC1zby1iZS1jYXJlZnVsLXRoYW5rLXlvdS1oYWhh
  access-token-expire-time: 60000
  refresh-token-expire-time: 604800000