name: test
on:
  push:
    branches:
      - main

jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest
    name: AUTO_DEPLOY
    steps:
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd mybox-clone
            git pull origin main
            ./gradlew build
            cd build/libs
            nohup java -jar mybox-clone-0.0.1-SNAPSHOT.jar &
#            source /etc/bash.bashrc
#            export MYSQL_DATABASE_URL="jdbc:mysql://localhost:3306/mybox"
#            export MYSQL_DATABASE_USERNAME="mybox"
#            export MYSQL_DATABASE_PASSWORD="mybox"

